test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

aliyun:
  service: Aliyun
  access_key_id: <%= Rails.application.credentials.dig(:aliyun_oss, :access_key_id) %>
  access_key_secret: <%= Rails.application.credentials.dig(:aliyun_oss, :access_key_secret) %>
  bucket: <%= Rails.application.credentials.dig(:aliyun_oss, :bucket) %>
  endpoint: <%= Rails.application.credentials.dig(:aliyun_oss, :endpoint) %>
  path: <%= Rails.application.credentials.dig(:aliyun_oss, :path) %>
  # Bucket mode: [public, private], default: public
  mode: "public"
